channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=24.3.1
- pip:
  - mlflow==2.22.0
  - aiohttp==3.11.18
  - cloudpickle==3.1.1
  - grpcio-status==1.71.0
  - ipython==9.1.0
  - langchain-google-genai==2.0.10
  - langgraph==0.3.27
  - opentelemetry-exporter-otlp-proto-grpc==1.32.1
  - opentelemetry-instrumentation-fastapi==0.53b1
  - pyreadline3==3.5.4
  - rich==14.0.0
name: mlflow-env
